GET http://localhost:5166/games

###
GET http://localhost:5166/games/5268f468-a14e-4565-888a-f38452591c95
###
POST http://localhost:5166/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 99.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5166/games/3da49022-2135-4f46-a79a-0aa69bd8360b
Content-Type: application/json

{
    "name": "Donkey Kong",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}