GET http://localhost:5166/games

###
GET http://localhost:5166/games/d812ed3a-86ec-4856-bb30-86a2edeb722d

###
POST http://localhost:5166/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 99.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5166/games/0455a4ae-4820-4a84-98c7-2a73887f6ce6
Content-Type: application/json

{
    "name": "sLego Batman",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5166/games/0455a4ae-4820-4a84-98c7-2a73887f6ce6